yaml
name: Auto Commit Changes

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "TuNombreDeUsuario"
          git config user.email "tuemail@example.com"

      - name: Make changes
        run: |
          # Aquí puedes colocar el script para hacer los cambios automáticos en tu código
          echo "Realizando cambios en el código"

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Guardado automático de cambios"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
